// angular_research_submit/src/app/components/new-playlist/new-playlist.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-new-playlist',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './new-playlist.component.html',
  styleUrls: ['./new-playlist.component.css'],
})
export class NewPlaylistComponent {
  name: string = '';
  isChecked: boolean = false;
  error: string | null = null;

  constructor(private router: Router, private http: HttpClient) {}

  async handleSubmit(event: Event) {
    event.preventDefault();
    this.error = null;
  
    try {
      const response = await this.http.post('/playlists', {
        name: this.name,
        isPublic: this.isChecked,
      }, { responseType: 'text' }).toPromise();
  
      this.router.navigate(['/']);
    } catch (error: any) {
      this.error = error.message || 'Failed to create playlist';
    }
  }
  
}
<!DOCTYPE html>

<form (submit)="handleSubmit($event)" class="p-4 border rounded">
    <label class="block mb-2">
      Playlist Name:

      <input
        type="text"
        name="playlistName"
        [(ngModel)]="name"
        class="border p-2 w-full rounded"
        required
      />
    </label>
  
    <label class="block mb-2">
      <input type="checkbox" name="isPublic" [(ngModel)]="isChecked" />
      Public
    </label>
  
    <button type="submit" class="mt-2 p-2 bg-blue-500 text-white rounded">
      Create Playlist
    </button>
  
    <p *ngIf="error" class="text-red-500 mt-2">{{ error }}</p>
  </form>

// hw3_submit/hw3/src/components/NewPlaylist.jsx
import { useState } from "react"
import { useNavigate } from "react-router-dom"

function NewPlaylist() {
  const [name, setName] = useState("")
  const [checked, setChecked] = useState(false)
  const [error, setError] = useState(null)
  const navigate = useNavigate()

  const handleSubmit = async (e) => {
    e.preventDefault()
    setError(null)

    const response = await fetch("/playlists", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name,
        isPublic: checked,
      }),
    })
    

    if (!response.ok) {
      const errorData = await response.json()
      throw new Error(errorData.errors?.map(err => err.msg).join(", ") || "Create playlist failed!")
    }

    navigate("/")
  }

  const handleChange = () => {
    setChecked(!checked)
  }

  return (
    <form onSubmit={handleSubmit} className="p-4 border rounded">
      <label className="block mb-2">
        Playlist Name:
        <input
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          className="border p-2 w-full rounded"
          required
        />
      </label>
      <Checkbox
        label="Public"
        value={checked}
        onChange={handleChange}
      />
      <button type="submit" className="mt-2 p-2 bg-blue-500 text-white rounded">
        Create Playlist
      </button>
    </form>
  )
}

const Checkbox = ({ label, value, onChange }) => {
  return (
    <label>
      <input type="checkbox" checked={value} onChange={onChange} />
      {label}
    </label>
  )
}

export default NewPlaylist
