// hw3_submit/hw3/src/components/PlaylistList.jsx
import { useState, useEffect } from "react"
import { Link } from "react-router-dom"

function PlaylistList() {
  const [playlists, setPlaylists] = useState([])

  useEffect(() => {
    fetch("/playlists")
      .then((res) => res.json())
      .then((data) => setPlaylists(data))
      .catch((err) => console.error("Error fetching playlists:", err))
  }, [])

  return (
    <div>
      <h1 className="text-xl font-bold">My Playlists</h1>
      <Link to="/new" className="p-2 bg-blue-500 text-white rounded">Create New Playlist</Link>

      {playlists.length === 0 ? (
        <p>No available playlist!</p>
      ) : (
        <ul>
          {playlists.map((playlist) => (
            <li key={playlist._id} className="p-2 border rounded my-2">
              <h2 className="text-lg font-semibold">{playlist.name}</h2>
              
              <p>{playlist.isPublic ? "Public" : "Private"}</p>
              <Link 
                to={`/edit/${playlist._id}`} 
                className="text-blue-500"
                state={{ isPublic: playlist.isPublic }}
              >
                Edit
              </Link>
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}

export default PlaylistList

// angular_research_submit/src/app/components/playlist-list/playlist-list.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

interface Playlist {
  _id: string;
  name: string;
  isPublic: boolean;
}

@Component({
  selector: 'app-playlist-list',
  standalone: true,  
  imports: [CommonModule, RouterModule],  
  templateUrl: './playlist-list.component.html',
  styleUrls: ['./playlist-list.component.css']
  
})
export class PlaylistListComponent implements OnInit {
  playlists: Playlist[] = [];

  constructor(private http: HttpClient, private router: Router) {}

  ngOnInit(): void {
    this.http.get<Playlist[]>('/playlists').subscribe({
      next: (data) => (this.playlists = data),
      error: (err) => console.error('Error fetching playlists:', err)
    });
  }

  navigateToEdit(playlist: Playlist): void {
    this.router.navigate([`/edit/${playlist._id}`], { state: { isPublic: playlist.isPublic } });
  }
}
<!DOCTYPE html>

<div>
    <h1 class="text-xl font-bold">My Playlists</h1>
    <a routerLink="/new" class="p-2 bg-blue-500 text-white rounded">New Playlist</a>
  
    <p *ngIf="playlists.length === 0">Playlist Unavailable!</p>
  
    <ul *ngIf="playlists.length > 0">
      <li *ngFor="let playlist of playlists" class="p-2 border rounded my-2">
        <h2 class="text-lg font-semibold">{{ playlist.name }}</h2>
        <p>{{ playlist.isPublic ? 'Public' : 'Private' }}</p>
        <a (click)="navigateToEdit(playlist)" class="text-blue-500 cursor-pointer">
          Edit
        </a>
      </li>
    </ul>
</div>
